### ISSUE TITLE
 Addition of a News Section

### ISSUE THREAD

**Issue by dindiarto** [icraf-indonesia/LUMENSR#8]
### Motivation
A News section will keep users informed of package updates, changes, and bug fixes, enhancing user experience and facilitating improved tracking of development progress.

### Steps for Implementation
1. Implement a `build_news` function in `R/build-news.R` which creates a `NEWS.md` file segmented by version headings.
   The headings should be in the following format:
2. The headings format:
{package name} 1.3.0
{package name} v1.3.0
Version 1.3.0
Changes in 1.3.0
Changes in v1.3.0
3. The function would be:
``` r
build_news(pkg = ".", override = list(), preview = NA)
```

Arguments:

- pkg: package path
- override: named list to override values in _pkgdown.yml
- preview: previews generated section if TRUE or if is.na(preview) & interactive() both TRUE

### Updating the News Section
1. Update NEWS.md with release notes for each new version, indicating major changes, minor improvements, and bug fixes.

Example:
``` md
# Package 1.0.0
## Major changes
* Feature updates

## Minor improvements and bug fixes
* Bug fixes (@githubusername, #100)
* Minor updates (#200)
```

2. CRAN release dates are added automatically to the heading. "Unreleased" added if not available on CRAN.
3. Use YAML to link to release announcements, control page settings, or suppress default addition of CRAN release dates.

``` yaml
news:
  releases:
  - text: "usethis 1.3.0"
    href: https://www.tidyverse.org/articles/2018/02/usethis-1-3-0/
  - text: "usethis 1.0.0 (and 1.1.0)"
    href: https://www.tidyverse.org/articles/2017/11/usethis-1.0.0/
  one_page: false
  cran_dates: false
  ```
